version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: person-postgres
    environment:
      POSTGRES_DB: studs
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data/var/lib/postgresql/data
    networks:
      - person-network

  liquibase:
    build: ./liquibase
    container_name: liquibase
    environment:
      LIQUIBASE_COMMAND_CHANGELOG_FILE: changelog-master.xml
      LIQUIBASE_COMMAND_DRIVER: org.postgresql.Driver
      LIQUIBASE_COMMAND_URL: jdbc:postgresql://postgres:5432/studs
      LIQUIBASE_COMMAND_USERNAME: ${DB_USERNAME}
      LIQUIBASE_COMMAND_PASSWORD: ${DB_PASSWORD}
      LIQUIBASE_SEARCH_PATH: /liquibase/changelog
    command:
      update
    restart: on-failure
    depends_on:
      - postgres
    volumes:
      - ./liquibase:/liquibase/changelog
      - ./postgresql-42.6.0.jar:/liquibase/lib/postgresql.jar
    networks:
      - person-network

volumes:
  postgres_data:

networks:
  person-network:
    driver: bridge